# Generated by Django 5.0.6 on 2026-05-02 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('primary_category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('applicable_laws', models.JSONField(default=list)),
                ('urgency', models.CharField(choices=[('critical', 'Critical — 24–72 hours'), ('high', 'High — 7–15 days'), ('medium', 'Medium — 30–60 days'), ('low', 'Low — No immediate deadline')], default='medium', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('language_detected', models.CharField(default='en', max_length=20)),
                ('key_facts', models.JSONField(default=list)),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('questions', 'Gathering Information'), ('generating', 'Generating Document'), ('document', 'Document Ready'), ('summary', 'Summary & Next Steps'), ('closed', 'Closed')], default='intake', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
