# Generated by Django 5.2.6 on 2026-05-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
